### PR TITLE
Potential fixes for missing elements of library

### LINKED ISSUE #1: I think this is not working for v7.0
Hi,

I tried to use your code and it looks like this is not working. The timestamp being encoded is in strange format, something like hex in terminal.

Could you please have a look at it for a second?

Thanks you so much for such an awesome library.

### PR DESCRIPTION
**Pull request by jaitaiwan**
It appears that the library didn't account for PKCS5 padding on the decrypted result. This change should help with that. FIxes #1

### CODE REVIEW

File: cipher.go [hunk 1]
```diff
@@ -11,20 +12,50 @@ type CryptStruct struct {
...
 	ctx := cipher.NewCBCDecrypter(c.cipher, c.iv)
+
+	// Ensure that the input meets the correct blocksize
+	if len(input)%c.cipher.BlockSize() != 0 {
+		return nil, ErrInvalidInput
+	}
+
 	text := input[c.cipher.BlockSize():]
 	ctx.CryptBlocks(text, text)
 	return input, nil
```
Comment (rajuaryan21) [inline cipher.go:39]: isn't it's 

return text, nil

Comment (jaitaiwan) [reply cipher.go]: I wish I'd seen this earlier haha
